# ================================================
# NAS İstemci Tanımları
# ================================================
 
# Localhost - radtest ve radclient ile test için
client localhost {
    ipaddr      = 127.0.0.1
    secret      = ${RADIUS_SECRET}
    shortname   = localhost
    nastype     = other
}
 
# Docker network içindeki tüm istemciler
client docker_network {
    ipaddr      = 172.16.0.0/12
    secret      = ${RADIUS_SECRET}
    shortname   = docker
    nastype     = other
}
 