# ================================================
# SQL Modül Konfigürasyonu (PostgreSQL)
# ================================================
sql {
    dialect     = "postgresql"
    driver      = "rlm_sql_postgresql"
 
    server      = "${POSTGRES_HOST}"
    port        = 5432
    login       = "${POSTGRES_USER}"
    password    = "${POSTGRES_PASSWORD}"
    radius_db   = "${POSTGRES_DB}"
 
    acct_table1         = "radacct"
    acct_table2         = "radacct"
    postauth_table      = "radpostauth"
    authcheck_table     = "radcheck"
    authreply_table     = "radreply"
    groupcheck_table    = "radgroupcheck"
    groupreply_table    = "radgroupreply"
    usergroup_table     = "radusergroup"
 
    # Şifreler veritabanında hash'li saklanıyor
    read_clients        = no
 
    pool {
        start       = 5
        min         = 4
        max         = 10
        idle_timeout = 200
        uses        = 0
        lifetime    = 0
        retry_delay = 30
    }
 
    read_groups     = yes
    read_profiles   = no
    deletestaledsessions = yes
}
 




